### ISSUE TITLE
Doesn't work with back button

### ISSUE THREAD

**Issue by niffin** [allpro/react-router-pause#2]
```
<ReactRouterPause
  handler={() => {
    return null;
  }}
/>
```

Hitting the browser back button doesn't unmount the component but still changes the URL.
I'm using `connected-react-router` -- could that be the cause?

**Comment by allpro** [comment]
> I'm using connected-react-router -- could that be the cause?

**Yes, I assume it probably is, since it works normally.** This helper uses the documented `history.block()` method to halt navigation, so _should work_ with any other helpers that properly supports RR4 functionality. 

I did a quick search for "connected-react-router" and "history.block()", but didn't find anything specific However I did find numerous Git issues for connected-react-router related to the `history` object, so there seems to be compatibility problems.

**To confirm, try blocking navigation yourself.** Inside any component that is a 'route', add this code: `this.props.history.block(() => false)`. This _should_ block any further navigation. If this doesn't work, then connected-react-router must be the problem.

(Sorry it took a few days to get to this.)

**Comment by niffin** [comment]
Thanks for the reply.

`this.props.history.block(() => false)` did work...and so did the code i wrote earlier so looks like everything's working as expected. 

I'm going to chalk it up to webpack, or my laptop needing a reboot, or some other ghost in the machine. :)

Thanks for sharing this module -- it's extremely useful (and made me look like a hero to product/design).

**Comment by artivilla** [comment]
Interesting, i'm running into the same issue but using the latest `@allpro/react-router-pause@1.1.3` and `react-router-dom@5.2` versions. The diff between and the demo is the usage of history.push() over router <Link />s. This is how I've organized my handler:
```
    function handleNavAttempt(
        navigation: {
            [key: string]: Function;
        },
        location: { pathname: string },
    ): null {
        /* ONLY matches when location is routingTo specific views */
        if (
			// check for location.pathnames here
        ) {
			// open custom dialog modal for confirmation
            });
        } else {
            navigation.resume(); // continue navigation
        }
        return null;
    }
```
with `<ReactRouterPause handler={handleNavAttempt} when={isFormDataDirty()} />`
I'm unclear if navigation.resume() is actually storing history since `history.goBack()` doesn't work specifically on components defining `<ReactRouterPause />`.

**Comment by artivilla** [comment]
React-Router v6 has a Prompt we can customize for our needs. I'm thinking of switching to this since it likely works well with router history: https://michaelchan-13570.medium.com/using-react-router-v4-prompt-with-custom-modal-component-ca839f5faf39. Thoughts?
